name: Tests
on: [push, pull_request]

jobs:
  build-and-test-project:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install -y --no-install-recommends cmake clang-14 llvm-14 python3 python3-pip libboost-program-options-dev
          pip3 install gcovr

      - name: Build library
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=g++-11 \
                -DCMAKE_C_COMPILER=gcc-11 \
                -DSHPXX_BUILD_DOCS=OFF \
                -DSHPXX_AUTORUN_TESTS=OFF \
                -DSHPXX_INSTRUMENT_COVERAGE=ON \
                ..
          make shpxx shpxx-tests -j $(nproc)

      - name: Run Tests
        run: |
          cd build
          make check

      - name: Add Test Report PR Annotations
        uses: mikepenz/action-junit-report@v3
        if: github.event_name == 'pull_request'
        with:
          report_paths: 'build/reports/shpxx-tests.xml'

      - name: Generate Coverage Report
        run: |
          cd build
          make coverage

      - name: Trim Report File Paths
        run: |
          sed "s|$PWD/||g" -i build/reports/shpxx-coverage.xml

      - name: Extract Coverage Percentage
        run: |
          RATE=$(grep -o -m 1 -P '(?<=line-rate=").*?(?=")' ./build/reports/shpxx-coverage.xml | head -1)
          PERCENT="$(echo "($RATE * 100)/1" | bc)"
          echo "COVERAGE_PERCENT=$PERCENT"
          echo "COVERAGE_PERCENT=$PERCENT" >> $GITHUB_ENV

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          auth: ${{ secrets.COVERAGE_GIST_TOKEN }}
          gistID: 56c30a4341e1e10532203e9ed00d12ce
          filename: shpxx-coverage-badge.json
          label: Coverage
          message: ${{ env.COVERAGE_PERCENT }}
          valColorRange: ${{ env.COVERAGE_PERCENT }}
          minColorRange: 60
          maxColorRange: 95

      - name: Coverage Summary
        uses: 5monkeys/cobertura-action@master
        if: github.event_name == 'pull_request'
        with:
          path: 'build/reports/shpxx-coverage.xml'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          only_changed_files: true
          show_line: true
          show_branch: true
          skip_covered: false
          minimum_coverage: 0
          fail_below_threshold: false
