name: Formatting
on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.16.1
        with:
          clangFormatVersion: 16

  cmake-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: PuneetMatharu/cmake-format-lint-action@v1.0.2
        with:
          args: --config-files .cmake-format.json --in-place
      - name: Check for changes
        run: git diff --exit-code
