name: Project formatting
on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          clangFormatVersion: 12
