name: Linting
on: [push]

jobs:
  clang-tidy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y clang-tidy-12 cmake
      - name: Generate compilation database
        run: |
          cmake -B build -DSHPXX_BUILD_DOCS=OFF
      - name: Run clang-tidy
        run: |
          ./tools/check-clang-tidy.sh
